language: php

php:
    - 7.1

addons:
    apt:
        packages:
            - cmake
            - graphviz

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 4f93efb4-ef5c-4a78-9d29-47f1a4df9879
  # Generate the docs only if master, the travis_build_docs is true and we can use secure variables
    - >-
      if [[ "$TRAVIS_BRANCH" = "master" && -n "$TRAVIS_BUILD_DOCS" && "$TRAVIS_PULL_REQUEST" = "false" ]] ; then
        cd $TRAVIS_BUILD_DIR
        source .ci/setup-ssh.sh || travis_terminate 1
        source .ci/generateDocumentation.sh || travis_terminate 1
      fi
